### ISSUE TITLE
seqbuddy rename ids

### ISSUE THREAD

**Issue by sellisd** [biologyguy/BuddySuite#83]
renaming ids in `seqbuddy` seems to have an issue with space characters:
e.g: with the file **`seq.fa`**:
```
>first example
actg
```

running command:
```
$>seqbuddy seq.fa -ri e E
```
I would expect the E to be capitalized. Instead I get no change under  `SeqBuddy 1.2beta (2016-09-13)`

**Comment by biologyguy** [comment]
This is actually an issue with the FASTA header itself. In the given example, 'first' is recognized as the sequence ID, and then 'example' is supporting meta data (because of the space). I haven't written a function similar to rename_ids for modifying meta data, but it wouldn't be hard to implement. I can put it on the 'wish list' for the next release if you like.

**Comment by sellisd** [comment]
Ok, I understand the behavior now, it would be helpful as a feature to be able to rename the meta-data also.

I came across the issue trying to make a consensus and rename the FASTA header:

e.g in file: **`aln.fa`**
```
>seq1
actg
>seq2
accg
```

```
alignbuddy -con aln.fa | seqbuddy -ri '^.*$' newName
```

this would be helpful in alignments with too many sequences.

PS. By the way thanks for this great tool!

**Comment by biologyguy** [comment]
Oh ya, I see. Personally, I would string one more command onto the back to strip off the meta data:

`alignbuddy aln.fa -con | seqbuddy -dm | seqbuddy -ri '.*' newName`

And seriously, thanks for the note. I haven't hit critical mass on this project yet, so it's really encouraging to hear from someone who's using it.

**Comment by biologyguy** [comment]
Finally implemented a solution to this. [Sb.amend_metadata](github.com/biologyguy/BuddySuite/wiki/SB-Amend-metadata).
